spring:
  application:
    name: co-salon-migration-pos365

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cosalon_ims?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: cosalon.vn

  jpa:
    open-in-view: true
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 200
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      apache:
        http: debug
      springframework:
        web:
          client:
            RestTemplate: debug
        jdbc:
          core: trace
  com:
    jidian:
      cosalon:
        migration:
          pos365: debug
---
spring:
  profiles: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://188.166.206.203:3306/cosalon_ims?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: cosalon.vn
